name: zego_uikit_prebuilt_live_audio_room
description: PrebuiltLiveAudioRoom is a Live Audio Room kit that provides a ready-made group voice chat that supports up to 8 hosts and co-hosts to connect with millions of users downstage.
version: 3.3.2
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room
screenshots:
  - description: "Live Audio Room Kit for pub.dev preview"
    path: images/preview.jpg

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.18.7
  zego_uikit_signaling_plugin: ^2.7.6
  zego_plugin_adapter: ^2.11.4
  file_picker: ^6.0.0

  flutter_styled_toast: ^2.2.1
  cached_network_image: ^3.3.0
  statemachine: ^3.3.1
  permission_handler: ^11.0.1
  # 1.18.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0 # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any
  lints: ^3.0.0

flutter:
  assets:
    - assets/icons/

topics:
  - audio
  - audio-room
  - audio-chat