name: zego_uikit_prebuilt_live_audio_room
description: PrebuiltLiveAudioRoom is a Live Audio Room kit that provides a ready-made group voice chat that supports up to 8 hosts and co-hosts to connect with millions of users downstage.
version: 2.11.2
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room
screenshots:
  - description: "Live Audio Room Kit for pub.dev preview"
    path: images/preview.jpg

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.12.0
  zego_uikit_signaling_plugin: ^2.5.0
  zego_plugin_adapter: ^2.7.0
  file_picker: any

  http: ^0.13.4
  flutter_styled_toast: ^2.1.3
  cached_network_image: ^3.2.3
  statemachine: ^3.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  assets:
    - assets/icons/
